[env:nodemcu-32s]
platform = espressif32@6.12.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    ESP32Async/AsyncTCP@3.3.2
    ESP32Async/ESPAsyncWebServer@3.6.0

